name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:

  build:
    uses: syntax-tm/SteamAchievementManager/.github/workflows/build.yml@main
  create-release:
    runs-on: windows-latest
    needs: [build]
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        path: artifacts
    - uses: ncipollo/release-action@v1
      with:
        artifacts: artifacts/*
        bodyFile: ./CHANGELOG.md
        draft: true