name: Create Release
run-name: ${{ github.event_name == 'workflow_dispatch' && inputs.version || github.ref_name }} by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: 'v0.0.1'
        type: string
  push:
    tags:
    - 'v*'

jobs:

  setup:
    runs-on: windows-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.validate-version.outputs.version }}
      version-prefix: ${{ steps.validate-version.outputs.version-prefix }}
      version-suffix: ${{ steps.validate-version.outputs.version-suffix }}
      is-prerelease: ${{ steps.validate-version.outputs.is-prerelease }}
    steps:
    - id: validate-version
      name: Validate Version
      run: |
        # if this is on a release tag push it will use the ref_name, otherwise on
        # workflow_dispatch the version is required
        $version = '${{ github.ref_name || inputs.version }}'
        $version = $version.TrimStart('v')

        Write-Host "Version: " -NoNewLine
        Write-Host "$($PSStyle.Foreground.BrightCyan)$version$($PSStyle.Reset)"

        if ([string]::IsNullOrEmpty($version)) { throw 'A release version was not specified.' }

        # TODO: validate the version number format with regex

        $parts = $version -split '-',2
        $prefix = $parts[0]
        $suffix = $parts[1]
        $isPrerelease = $suffix -ne $null

        Write-Host "Prefix: " -NoNewLine
        Write-Host "$($PSStyle.Foreground.BrightCyan)$prefix$($PSStyle.Reset)"

        Write-Host "Suffix: " -NoNewLine
        Write-Host "$($PSStyle.Foreground.BrightCyan)$suffix$($PSStyle.Reset)"

        echo "version=$version" >> $env:GITHUB_OUTPUT
        echo "version-prefix=$prefix" >> $env:GITHUB_OUTPUT
        echo "version-suffix=$suffix" >> $env:GITHUB_OUTPUT
        echo "is-prerelease=$isPrerelease" >> $env:GITHUB_OUTPUT
  build:
    uses: syntax-tm/SteamAchievementManager/.github/workflows/build.yml@main
    needs: setup
    with:
      is_release: true
      version: ${{ needs.setup.outputs.version }}
  release:
    runs-on: windows-latest
    needs: [setup, build]
    permissions:
      contents: write
    steps:
    - id: checkout
      name: checkout
      uses: actions/checkout@v4
    - id: download-artifact
      name: download-artifact
      uses: actions/download-artifact@v4
      with:
        path: artifacts
      env:
        artifact-name: ${{ needs.build.outputs.artifact-name }}
    - id: create-archive
      name: create-archive
      run: |
        $items = Get-ChildItem artifacts
        $artifactName = "SAM_${{ needs.setup.outputs.version }}"

        Write-Host "Artifacts:"

        foreach ($item in $items)
        {
          Write-Host "- $($PSStyle.Foreground.BrightCyan)$($item.Name)$($PSStyle.Reset)"
        }

        $items | % { Compress-Archive -Path "$($_.FullName)\*" -DestinationPath "$($_.FullName).zip" -Force }

        Get-ChildItem -Path artifacts -Filter *.zip | Format-Table
    - id: create-release
      name: create-release
      uses: ncipollo/release-action@v1
      with:
        artifacts: artifacts/*.zip
        bodyFile: ./CHANGELOG.md
        draft: true
        allowUpdates: true
        artifactErrorsFailBuild: true
        omitBodyDuringUpdate: true
        omitDraftDuringUpdate: true
        omitNameDuringUpdate: true
        prerelease: ${{ needs.setup.outputs.is-prerelease == 'true' && 'true' || '' }}
    - id: summary
      name: summary
      run: |
        $url = "${{ steps.create-release.outputs.html_url }}"
        $name = "${{ needs.setup.outputs.version }}"
        $preRelease = "${{ needs.setup.outputs.is-prerelease == 'true' && 'Yes' || 'No' }}"

        $md = "# Release`n"
        $md += "`n"
        $md += "- **Version:** $name`n"
        $md += "- **Prerelease:** $preRelease`n"
        $md += "- **Url:** [$name]($url)`n"

        $md >> $env:GITHUB_STEP_SUMMARY