name: Test

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: List Files
      run: ls --group-directories-first -pNFlh
